//! Liquidity — funds sweep, cash pooling, and zero-balance structures.
//!
//! Pure M2. These are scheduled inter-account postings generated by temporal rules, and the
//! scope names the property they must have: **provably balanced by construction**.
//!
//! # Why these are the cleanest test of M2
//!
//! A sweep has no valuation, no counterparty and no lifecycle. It is a rule that says *move
//! whatever it takes to bring this account to its target*, applied on a schedule. That
//! makes it the product where the schedule mechanism is doing all the work and nothing else
//! is, so if M2's "balanced by construction" claim is going to fail anywhere it will fail
//! here first.
//!
//! It also has the property that makes scheduled movement dangerous in practice: **the
//! amount is not known when the rule is written.** A coupon's amount is fixed at trade
//! date; a sweep's is whatever the balance happens to be at 4 p.m. A system that stored
//! amounts could not express a sweep at all, which is why M2 stores generators.
//!
//! # The header account is a participant, not a plug
//!
//! In a cash pool, subsidiary balances are swept to a header account. The header is a real
//! account belonging to a real legal entity, and the sweep creates an intercompany
//! receivable or payable that has tax and regulatory consequences. Modelling the header as
//! a balancing figure — the way a naive implementation would — produces a pool that
//! balances and an intercompany position nobody booked.

use gbs_kernel::{Amount, Chart, Currency, Entry, Epoch, PostingSet, Stamp};
use gbs_mechanisms::{Generator, Observations, Occurrence, Reading, Schedule, ScheduleError};

/// How a sweep decides what to move.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    /// Move everything to the header, leaving nothing. A zero-balance account.
    Zero,
    /// Leave a fixed balance behind, moving only the excess. The common cash-management
    /// arrangement, where an operating account keeps a working float.
    Retain(i128),
    /// Move only what exceeds a threshold, and only in that direction. A one-way sweep:
    /// it never funds a shortfall, which matters where the subsidiary must not be lent to.
    ExcessOver(i128),
}

impl Target {
    /// What to move, given a balance. Positive moves *to* the header; negative moves *from*
    /// it, funding a shortfall.
    ///
    /// Takes a [`Reading`] rather than an amount, so an unknown balance produces no
    /// movement rather than a movement computed from an assumed zero. A sweep that fired
    /// against a missing balance would drain an account whose position nobody could
    /// compute — which is the `Err(_) => 0` defect with a scheduler attached to it.
    pub fn movement(&self, balance: &Reading) -> Option<i128> {
        let b = balance.amount()?.minor;
        let m = match self {
            Target::Zero => b,
            Target::Retain(keep) => b - keep,
            Target::ExcessOver(threshold) => {
                if b > *threshold {
                    b - threshold
                } else {
                    // One-way: never funds a shortfall.
                    0
                }
            }
        };
        if m == 0 {
            // No movement is not a transaction. Returning `Some(0)` would produce a posting
            // set of two zero legs, which conserves but records a sweep that did not
            // happen — and a nightly report counting sweeps would be wrong.
            None
        } else {
            Some(m)
        }
    }
}

/// One participant account in a pool.
#[derive(Debug, Clone)]
pub struct PoolAccount {
    pub account: String,
    pub target: Target,
}

/// A cash pool: participants swept to a header on a schedule.
pub struct Pool {
    pub id: String,
    pub header: String,
    pub participants: Vec<PoolAccount>,
    pub currency: Currency,
}

impl Pool {
    pub fn new(id: &str, header: &str, currency: &str) -> Self {
        Pool {
            id: id.to_string(),
            header: header.to_string(),
            participants: Vec::new(),
            currency: Currency::new(currency),
        }
    }

    pub fn with(mut self, account: &str, target: Target) -> Self {
        self.participants.push(PoolAccount { account: account.to_string(), target });
        self
    }

    /// The sweep generator.
    ///
    /// Takes a balance lookup, which is how the amount that is not known at declaration
    /// time enters the rule. The lookup returns a [`Reading`], so an account whose balance
    /// cannot be computed is skipped rather than swept to zero.
    ///
    /// **Balanced by construction**: each participant's movement is mirrored to the header,
    /// so the set sums to zero however many participants there are and whatever their
    /// balances turn out to be. There is no path by which a sweep can be unbalanced.
    pub fn generator<F>(&self, balances: F, scale: u32) -> Generator
    where
        F: Fn(&str, i64) -> Reading + 'static,
    {
        let header = self.header.clone();
        let participants = self.participants.clone();
        let currency = self.currency.clone();
        let id = self.id.clone();

        Box::new(move |occ: &Occurrence, _obs: &Observations| {
            let mut ps = PostingSet::new(format!("sweep-{}-{}", id, occ.index));
            let mut next_id = 1u64;
            let mut moved_any = false;

            for p in &participants {
                let balance = balances(&p.account, occ.adjusted);
                let Some(movement) = p.target.movement(&balance) else {
                    continue;
                };
                // Out of the participant, into the header. Mirrored, so the pair balances
                // whatever `movement` turns out to be.
                let out = Entry::new(
                    next_id,
                    p.account.clone(),
                    Amount::new(-movement, currency.clone(), scale),
                    Stamp::new(Epoch(0), occ.adjusted),
                )
                .narrated(format!("sweep to {header} under {id}"));
                let into = out.mirrored_to(next_id + 1, header.clone()).ok()?;
                ps.push(out);
                ps.push(into);
                next_id += 2;
                moved_any = true;
            }

            // No participant moved: the pool is already at target. `None`, not an empty
            // set — the kernel would refuse an empty one, and the two layers agree that a
            // sweep which moved nothing is not a transaction.
            if moved_any {
                Some(ps)
            } else {
                None
            }
        })
    }

    /// Build the sweep schedule.
    pub fn schedule<F>(
        &self,
        effective: i64,
        maturity: i64,
        every_days: i64,
        balances: F,
        scale: u32,
    ) -> Result<Schedule, ScheduleError>
    where
        F: Fn(&str, i64) -> Reading + 'static,
    {
        Schedule::new(
            format!("{}-sweep", self.id),
            effective,
            maturity,
            every_days,
            self.generator(balances, scale),
        )
    }

    /// Check the generator before installing the structure.
    pub fn check<C: gbs_mechanisms::Calendar, F>(
        &self,
        cal: &C,
        chart: &Chart,
        effective: i64,
        maturity: i64,
        every_days: i64,
        balances: F,
        scale: u32,
    ) -> Result<(), ScheduleError>
    where
        F: Fn(&str, i64) -> Reading + 'static,
    {
        self.schedule(effective, maturity, every_days, balances, scale)?
            .check_generator(cal, chart, &[Observations::new()])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gbs_kernel::Account;
    use gbs_mechanisms::AllDays;
    use std::collections::BTreeMap;

    fn usd(m: i128) -> Amount {
        Amount::minor_2dp(m, "USD")
    }

    fn chart() -> Chart {
        Chart::new()
            .with(Account::new("header.usd", "group", "USD"))
            .with(Account::new("sub-a.usd", "sub-a", "USD"))
            .with(Account::new("sub-b.usd", "sub-b", "USD"))
            .with(Account::new("sub-c.usd", "sub-c", "USD"))
    }

    /// A balance oracle for the tests: a fixed map, with anything unlisted absent.
    fn balances(m: BTreeMap<&'static str, i128>) -> impl Fn(&str, i64) -> Reading + 'static {
        move |account, _day| match m.get(account) {
            Some(v) => Reading::Present(usd(*v)),
            None => Reading::Absent,
        }
    }

    fn pool() -> Pool {
        Pool::new("pool-1", "header.usd", "USD")
            .with("sub-a.usd", Target::Zero)
            .with("sub-b.usd", Target::Retain(10_000))
            .with("sub-c.usd", Target::ExcessOver(50_000))
    }

    // ── balanced by construction ────────────────────────────────────────────────────

    #[test]
    fn a_sweep_conserves_whatever_the_balances_turn_out_to_be() {
        // The property M2 exists to provide, and the one a sweep is the cleanest test of:
        // the amounts are not known when the rule is written, and the rule is balanced
        // anyway.
        let ch = chart();
        for (a, b, c) in [
            (100_000i128, 75_000i128, 90_000i128),
            (0, 0, 0),
            (-50_000, 10_000, 50_001),
            (1, 10_001, 49_999),
            (i64::MAX as i128, 10_000, 50_000),
        ] {
            let m = BTreeMap::from([("sub-a.usd", a), ("sub-b.usd", b), ("sub-c.usd", c)]);
            let s = pool().schedule(0, 90, 30, balances(m), 2).unwrap();
            for (_, ps) in s.generate(&AllDays, 30, Epoch(1), &Observations::new()).unwrap() {
                ps.seal(&ch, Epoch(1)).unwrap_or_else(|e| {
                    panic!("sweep with balances ({a}, {b}, {c}) failed to conserve: {e}")
                });
            }
        }
    }

    #[test]
    fn the_generator_passes_the_declaration_time_check() {
        let m = BTreeMap::from([("sub-a.usd", 100_000i128), ("sub-b.usd", 75_000), ("sub-c.usd", 90_000)]);
        pool().check(&AllDays, &chart(), 0, 360, 30, balances(m), 2).unwrap();
    }

    // ── the three targets ───────────────────────────────────────────────────────────

    #[test]
    fn a_zero_balance_account_is_swept_flat() {
        assert_eq!(Target::Zero.movement(&Reading::Present(usd(100_000))), Some(100_000));
        assert_eq!(Target::Zero.movement(&Reading::Present(usd(-25_000))), Some(-25_000),
            "and a negative balance is funded from the header");
    }

    #[test]
    fn a_retaining_account_keeps_its_float_and_moves_only_the_excess() {
        let t = Target::Retain(10_000);
        assert_eq!(t.movement(&Reading::Present(usd(75_000))), Some(65_000));
        assert_eq!(t.movement(&Reading::Present(usd(10_000))), None, "already at target");
        assert_eq!(t.movement(&Reading::Present(usd(5_000))), Some(-5_000), "topped up to the float");
    }

    #[test]
    fn a_one_way_sweep_never_funds_a_shortfall() {
        // The arrangement where the subsidiary must not be lent to — an intercompany loan
        // the structure is specifically designed not to create.
        let t = Target::ExcessOver(50_000);
        assert_eq!(t.movement(&Reading::Present(usd(90_000))), Some(40_000));
        assert_eq!(t.movement(&Reading::Present(usd(50_000))), None);
        assert_eq!(
            t.movement(&Reading::Present(usd(10_000))),
            None,
            "below the threshold, a one-way sweep does nothing"
        );
    }

    // ── honest absence, with a scheduler attached ───────────────────────────────────

    #[test]
    fn an_account_with_an_unknown_balance_is_skipped_rather_than_swept_to_zero() {
        // The `Err(_) => 0` defect with the worst possible consequence: a scheduled job
        // that drains an account whose position nobody could compute. `Reading` makes it
        // unrepresentable, and this is the test that says so.
        assert_eq!(Target::Zero.movement(&Reading::Absent), None);
        assert_eq!(Target::Zero.movement(&Reading::Unavailable("fold failed".into())), None);
        assert_eq!(Target::Retain(10_000).movement(&Reading::Absent), None,
            "and it is not topped up to its float either");
    }

    #[test]
    fn a_pool_with_one_unreadable_account_still_sweeps_the_others_correctly() {
        // Partial failure must not become total failure *or* silent corruption. The
        // readable accounts sweep, the unreadable one does not, and the set still conserves.
        let ch = chart();
        let m = BTreeMap::from([("sub-a.usd", 100_000i128), ("sub-c.usd", 90_000)]);
        // sub-b is absent from the map, so its balance reads Absent.
        let s = pool().schedule(0, 90, 30, balances(m), 2).unwrap();
        let out = s.generate(&AllDays, 30, Epoch(1), &Observations::new()).unwrap();
        assert_eq!(out.len(), 1);
        let sealed = out[0].1.clone().seal(&ch, Epoch(1)).unwrap();
        assert_eq!(sealed.entries().len(), 4, "two accounts swept, two legs each");
        assert!(
            !sealed.entries().iter().any(|e| e.account.as_str() == "sub-b.usd"),
            "the unreadable account was skipped, not swept"
        );
    }

    // ── no movement is not a transaction ────────────────────────────────────────────

    #[test]
    fn a_pool_already_at_target_produces_no_posting_set_at_all() {
        // Not an empty one — the kernel would refuse that — and not two zero legs, which
        // would record a sweep that did not happen and make a nightly count wrong.
        let m = BTreeMap::from([("sub-a.usd", 0i128), ("sub-b.usd", 10_000), ("sub-c.usd", 50_000)]);
        let s = pool().schedule(0, 90, 30, balances(m), 2).unwrap();
        assert!(s.generate(&AllDays, 30, Epoch(1), &Observations::new()).unwrap().is_empty());
    }

    // ── the header is a real account ────────────────────────────────────────────────

    #[test]
    fn every_sweep_creates_a_matching_leg_on_the_header() {
        // The header is a participant, not a balancing figure. Each subsidiary's movement
        // has its own header leg, so the intercompany position is booked per subsidiary
        // rather than netted into one number nobody can decompose.
        let ch = chart();
        let m = BTreeMap::from([("sub-a.usd", 100_000i128), ("sub-b.usd", 75_000), ("sub-c.usd", 90_000)]);
        let s = pool().schedule(0, 90, 30, balances(m), 2).unwrap();
        let out = s.generate(&AllDays, 30, Epoch(1), &Observations::new()).unwrap();
        let sealed = out[0].1.clone().seal(&ch, Epoch(1)).unwrap();

        let header_legs: Vec<_> =
            sealed.entries().iter().filter(|e| e.account.as_str() == "header.usd").collect();
        assert_eq!(header_legs.len(), 3, "one header leg per sweeping subsidiary");
        assert_eq!(
            header_legs.iter().map(|e| e.amount.minor).sum::<i128>(),
            100_000 + 65_000 + 40_000
        );
    }

    #[test]
    fn a_zero_balance_structure_is_the_same_machinery_with_one_target() {
        // ZBA is not a separate product; it is a pool whose participants all target zero.
        // The generality claim, at its smallest scale.
        let zba = Pool::new("zba-1", "header.usd", "USD")
            .with("sub-a.usd", Target::Zero)
            .with("sub-b.usd", Target::Zero);
        let m = BTreeMap::from([("sub-a.usd", 33_333i128), ("sub-b.usd", -12_121)]);
        let s = zba.schedule(0, 30, 1, balances(m), 2).unwrap();
        let out = s.generate(&AllDays, 1, Epoch(1), &Observations::new()).unwrap();
        let sealed = out[0].1.clone().seal(&chart(), Epoch(1)).unwrap();
        assert_eq!(sealed.entries().len(), 4);
        sealed.verify().unwrap();
    }

    #[test]
    fn sweeps_are_deterministic_across_repeated_generation() {
        let m = BTreeMap::from([("sub-a.usd", 100_000i128), ("sub-b.usd", 75_000), ("sub-c.usd", 90_000)]);
        let s = pool().schedule(0, 90, 30, balances(m), 2).unwrap();
        let first = s.generate(&AllDays, 30, Epoch(1), &Observations::new()).unwrap();
        for _ in 0..20 {
            assert_eq!(s.generate(&AllDays, 30, Epoch(1), &Observations::new()).unwrap(), first);
        }
    }
}
