//! **The memory gate.** Every E18 scenario is held to its allocations-per-operation budget.
//!
//! `#[ignore]`d, and run explicitly by `make gate` and `make reproduce`:
//!
//! ```sh
//! cargo test --release --manifest-path tools/memprobe/Cargo.toml \
//!       -- --ignored --test-threads=1
//! ```
//!
//! Two things in that command line are load-bearing rather than incidental.
//!
//! **`--release`.** An allocation count is exact *within a build profile* and not across one:
//! the same served query allocates 173,363 times in release and 341,918 in debug, because
//! inlining and `Vec` growth differ. The published table is generated by the release binary,
//! so the gate that holds it must be the same build. A budget that passed in one profile and
//! failed in the other would be a gate nobody could act on.
//!
//! **`--test-threads=1`.** The counters are process-global, because a `#[global_allocator]`
//! is. A second test allocating on another thread is counted into whatever region is being
//! measured, silently and by a different amount every run. `a_quiet_region_is_quiet` fires
//! first and says so rather than letting every number below drift.
//!
//! What this gate catches that a wall-clock table cannot: an optimisation that *moves*
//! allocations instead of removing them. A fold that stops building a Z-set and starts
//! building a `Vec` per row looks identical in a noisy wall-clock median.

use memprobe::alloc::{self as memory, budget, SCENARIOS};
use memprobe::scenarios as scenarios_e18;

#[global_allocator]
static COUNTING: memory::Counting = memory::Counting;

#[test]
fn the_counting_allocator_is_actually_installed() {
    // The failure that would make every budget below vacuous: without the allocator the
    // counters read zero and everything passes. Probed rather than assumed.
    assert!(
        memory::installed(),
        "the counters are not live, so every budget would pass on a table of zeros"
    );
    let (_, c) = memory::count(|| {
        let v: Vec<u64> = (0..1_000).collect();
        std::hint::black_box(v.len())
    });
    assert!(c.allocations > 0 && c.bytes >= 8_000, "{c:?}");
}

#[test]
fn every_measured_scenario_has_a_budget_and_the_lists_agree() {
    // Cheap and parallel-safe: no measurement, only the bookkeeping. A scenario that stopped
    // being measured would leave its budget in place, passing forever against nothing.
    for s in SCENARIOS {
        assert!(budget(s).is_some(), "`{s}` is measured and has no budget");
    }
}

#[test]
#[ignore = "a measurement: run with --release -- --ignored --test-threads=1"]
fn every_scenario_is_within_its_allocation_budget() {
    // **The counters must be live in the process that reads them.** `make memory` runs this
    // binary with `--ignored`, which filters out `the_counting_allocator_is_actually_installed`
    // — so before this gate existed the only check that the allocator was installed was in a
    // test the gate did not run. Without the allocator every counter reads zero and every
    // budget below passes on a table of zeros, which is the one failure that would make this
    // whole file vacuous. Probed here, in the test that uses the numbers.
    assert!(
        memory::installed(),
        "the counting allocator is not live in this process, so every budget below would pass \
         against zeros. Re-run with the budget test's own `#[global_allocator]` in scope."
    );
    a_quiet_region_is_quiet();
    // Not `assert!(!cfg!(debug_assertions))`: that is a constant, and clippy is right to
    // refuse it. Read at run time so the message is what a reader gets rather than a
    // compile-time tautology.
    if std::hint::black_box(cfg!(debug_assertions)) {
        panic!(
            "an allocation count is exact within a build profile and not across one — the \
             same served query allocates 173,363 times in release and 341,918 in debug. The \
             published table is a release build, so this gate must be: re-run with --release."
        );
    }

    let measured: Vec<&str> = scenarios_e18::all().iter().map(|r| r.scenario).collect();
    assert_eq!(
        measured, SCENARIOS,
        "the published scenario list and what `all()` measures have drifted"
    );

    let mut over = Vec::new();
    for row in scenarios_e18::all() {
        let b = budget(row.scenario).expect("checked above");
        if row.allocations_per_op() > b {
            over.push(format!(
                "  {} — {:.1} allocations per {} against a budget of {:.1} ({} allocations \
                 over {} operations)",
                row.scenario,
                row.allocations_per_op(),
                row.unit,
                b,
                row.counted.allocations,
                row.operations
            ));
        }
    }
    assert!(
        over.is_empty(),
        "{} scenario(s) allocate more per operation than their budget allows. An allocation \
         count is exact, so this is a change in the program and not in the machine:\n{}",
        over.len(),
        over.join("\n")
    );
}

/// Measure a region that allocates nothing, and require the counters to agree.
///
/// The contamination check. The counters are process-global, so a test allocating on another
/// thread lands in whatever region is being measured — silently, and by a different amount
/// each run. This turns that into an instruction instead of a wrong number.
fn a_quiet_region_is_quiet() {
    let (_, c) = memory::count(|| std::hint::black_box(1u64 + 1));
    assert_eq!(
        c.allocations, 0,
        "{} allocations arrived during a region that allocates nothing, so another thread is \
         allocating into these counters. Re-run with --test-threads=1.",
        c.allocations
    );
}
