[package]
name = "experiments"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
niles-lang = { path = "../niles-lang" }
proto-engine = { path = "../proto-engine" }
nilestream-ledger = { path = "../nilestream-ledger" }

[[bin]]
name = "experiments"
path = "src/main.rs"
