#!/usr/bin/env python3
"""Inventory every MISMATCH-* and BLOCKED-* marker in this repository.

**Why a script rather than a shell one-liner.** `docs/audit/cycle-11/markers-653a369.txt`
listed 34 distinct markers where an unrestricted grep at the same commit found 50. Three
reasons, all of them the kind that make an inventory quietly smaller rather than wrong:

* it excluded `docs/audit/**`, which is where most markers are raised;
* it truncated each name at the first `_`, so `BLOCKED-LC20-definition` and
  `BLOCKED-LC20_definition` could not both be seen and some names lost their tail;
* it walked the working tree, so an untracked file (`target/inventory-leak.niles`) was
  counted as though it were part of the repository.

A smaller inventory looks exactly like a complete one. So this reads **tracked files only**,
at a named commit, over the whole tree including `docs/audit/`, and takes each marker's whole
name; and `tests/markers_inventory.rs` asserts that the committed file equals what this
prints, so the two cannot drift.

    python3 docs/audit/tools/markers.py <commit>            # print the inventory
    python3 docs/audit/tools/markers.py <commit> --write <path>
    python3 docs/audit/tools/markers.py --self-test

The output is one line per distinct marker, sorted, with its occurrence count and the tracked
files it appears in. Occurrence counts and file lists are what a reader needs to decide
whether a marker is live or historical; **this script does not decide that** — it counts.
Cycle 11 recorded a disagreement between two auditors about whether `MISMATCH-A9-F05` is
active, and a tool that guessed would have hidden it.
"""

import re
import subprocess
import sys

# The whole name, `-` and `_` included, stopping at the first character that cannot be part
# of one. Truncating at `_` is what lost tails from the previous inventory.
MARKER = re.compile(r"\b(?:MISMATCH|BLOCKED)-[A-Za-z0-9_-]+")

# Extensions whose contents are text we can scan. A marker inside a binary is not a marker
# anyone reads, and decoding one produces noise that looks like a finding.
SKIP_SUFFIX = (".pdf", ".png", ".jpg", ".gz", ".zip", ".bundle", ".DS_Store")


def tracked_files(commit):
    """Every tracked path at `commit`. Tracked, so an untracked scratch file cannot enter."""
    out = subprocess.run(
        ["git", "ls-tree", "-r", "--name-only", commit],
        capture_output=True,
        text=True,
        check=True,
    )
    return [p for p in out.stdout.splitlines() if not p.endswith(SKIP_SUFFIX)]


def inventory(commit):
    """`{marker: {path: count}}` over the tracked tree at `commit`."""
    found = {}
    for path in tracked_files(commit):
        blob = subprocess.run(
            ["git", "show", f"{commit}:{path}"], capture_output=True, check=False
        )
        text = blob.stdout.decode("utf-8", errors="replace")
        for m in MARKER.findall(text):
            found.setdefault(m, {}).setdefault(path, 0)
            found[m][path] += 1
    return found


def render(commit, found):
    lines = [
        f"# MISMATCH-* and BLOCKED-* markers at {commit}",
        "#",
        "# Generated by docs/audit/tools/markers.py over TRACKED files only, including",
        "# docs/audit/**, with each marker's whole name. Occurrences and files are counted;",
        "# whether a marker is live or historical is a reader's judgement and not this",
        "# file's. Regenerate with:",
        f"#     python3 docs/audit/tools/markers.py {commit} --write <this file>",
        "#",
        f"# {len(found)} distinct marker(s), "
        f"{sum(sum(f.values()) for f in found.values())} occurrence(s).",
        "",
    ]
    for marker in sorted(found):
        files = found[marker]
        total = sum(files.values())
        where = "; ".join(f"{p}:{n}" for p, n in sorted(files.items()))
        lines.append(f"{marker}: {total} occ in {len(files)} file(s); {where}")
    return "\n".join(lines) + "\n"


def self_test():
    """The three faults that made the previous inventory smaller, each as a case."""
    ok = True

    def check(name, got, want):
        nonlocal ok
        if got == want:
            print(f"  ok      : {name}")
        else:
            print(f"  FAILED  : {name}\n            got {got!r}\n            want {want!r}")
            ok = False

    check(
        "a name is taken whole, not truncated at the first underscore",
        MARKER.findall("see BLOCKED-LC20_definition today"),
        ["BLOCKED-LC20_definition"],
    )
    check(
        "a hyphenated tail survives",
        MARKER.findall("BLOCKED-branch-C11-03 stands"),
        ["BLOCKED-branch-C11-03"],
    )
    check(
        "two markers on one line are two markers",
        MARKER.findall("MISMATCH-A9-F05 and BLOCKED-LC20-definition"),
        ["MISMATCH-A9-F05", "BLOCKED-LC20-definition"],
    )
    check(
        "a word that merely contains the prefix is not a marker",
        MARKER.findall("UNBLOCKED-thing NOTMISMATCH-x"),
        [],
    )
    check(
        "a bare prefix with no name is not a marker",
        MARKER.findall("BLOCKED- and MISMATCH-"),
        [],
    )
    # The scan's scope is the other half of the fault, and it is structural: `tracked_files`
    # asks git, so an untracked file cannot appear and `docs/audit/**` is not excluded.
    files = tracked_files("HEAD")
    check("docs/audit is in scope", any(p.startswith("docs/audit/") for p in files), True)
    check(
        "untracked files are out of scope",
        subprocess.run(
            ["git", "ls-files", "--others", "--exclude-standard"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        == ""
        or all(
            p
            not in subprocess.run(
                ["git", "ls-files", "--others", "--exclude-standard"],
                capture_output=True,
                text=True,
                check=True,
            ).stdout.split()
            for p in files
        ),
        True,
    )
    print("\n=== self-test: " + ("every case holds" if ok else "FAILED"))
    return 0 if ok else 1


def main(argv):
    if "--self-test" in argv:
        return self_test()
    if not argv:
        print(__doc__)
        return 2
    commit = argv[0]
    text = render(commit, inventory(commit))
    if "--write" in argv:
        path = argv[argv.index("--write") + 1]
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {path}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
