//! **E18 — memory, counted.** Writes `results/E18-memory.csv` and `results/E18-memory.md`.
//!
//! ```sh
//! cargo run --release --manifest-path tools/memprobe/Cargo.toml -- e18
//! ```
//!
//! Single-threaded on purpose: the counters are process-global, because a
//! `#[global_allocator]` is, and a second thread allocating during a measured region lands
//! in it.

use memprobe::alloc::{self, CSV_HEADER};
use std::fmt::Write as _;

#[global_allocator]
static COUNTING: alloc::Counting = alloc::Counting;

/// The repository root, from this package's own location, so the results land beside every
/// other experiment's however the binary was invoked.
fn root() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("the repository root is two levels above this manifest")
}

fn main() {
    if !alloc::installed() {
        eprintln!(
            "memprobe: the counting allocator is not installed, so every counter would read \
             zero and a table of zeros is indistinguishable from a program that allocates \
             nothing."
        );
        std::process::exit(2);
    }
    println!("[E18] Memory, counted (allocations are exact; no wall clock appears here)");
    let rows = memprobe::scenarios::all();

    let mut csv = String::from(CSV_HEADER);
    csv.push('\n');
    for r in &rows {
        writeln!(csv, "{}", r.to_csv()).ok();
    }

    let mut md = String::new();
    md.push_str("# E18 — Memory, counted\n\n");
    md.push_str(
        "**Generated by `cargo run --release --manifest-path tools/memprobe/Cargo.toml -- \
         e18`. Nothing in this file is typed in by hand, and nothing in it depends on the \
         host.**\n\n\
         Before this experiment the project had no memory instrument: no allocation counter, \
         no bytes-per-posting figure, no threshold in any gate. \"Highly efficient in \
         memory\" was a goal with nothing to measure it against — an improvement could not be \
         claimed and a regression could not be caught.\n\n\
         Allocation counts are **deterministic**, which is why they and not wall clock are \
         what the gate asserts. `bytes` is requested bytes, not resident set: the allocator's \
         own bookkeeping is excluded on purpose, because it is a property of the allocator \
         and this measures the program. `live` is what the region still held when it ended; \
         `peak` is its high-water mark, which is what decides whether a query fits.\n\n\
         The tool lives outside the workspace. `GlobalAlloc` cannot be implemented without \
         `unsafe`, and §9.10 claims the workspace contains none — a claim about the system, \
         which this is not part of.\n\n",
    );
    md.push_str(
        "| Scenario | Unit | Ops | Allocations | per op | Bytes | per op | Live | Peak |\n",
    );
    md.push_str("|---|---|--:|--:|--:|--:|--:|--:|--:|\n");
    for r in &rows {
        writeln!(
            md,
            "| `{}` | {} | {} | {} | {:.1} | {} | {:.0} | {} | {} |",
            r.scenario,
            r.unit,
            r.operations,
            r.counted.allocations,
            r.allocations_per_op(),
            r.counted.bytes,
            r.bytes_per_op(),
            r.counted.live_delta,
            r.counted.peak_delta
        )
        .ok();
    }
    md.push_str("\n## The budgets, and what breaches one\n\n");
    md.push_str(
        "Allocations per operation, asserted exactly — an allocation count is not a \
         tolerance. Bytes and live figures are reported and not asserted: they move with a \
         `Vec`'s growth policy in ways that are not a regression.\n\n",
    );
    md.push_str(
        "| Scenario | Budget (allocations/op) | Measured | Headroom |\n|---|--:|--:|--:|\n",
    );
    for r in &rows {
        let b = alloc::budget(r.scenario).unwrap_or(f64::INFINITY);
        writeln!(
            md,
            "| `{}` | {:.1} | {:.1} | {:.0}% |",
            r.scenario,
            b,
            r.allocations_per_op(),
            (b - r.allocations_per_op()) / b * 100.0
        )
        .ok();
    }
    md.push_str(
        "\n## What this does not measure\n\n\
         Resident set, fragmentation and the allocator's own overhead — for those, `valgrind \
         --tool=massif` and `--tool=dhat`, whose commands are in `docs/BENCHMARK.md`. They \
         are not in a gate because their output is neither deterministic in the same way nor \
         cheap.\n\n\
         Nothing here is a *speed* claim. A fold that allocates once per query may still be \
         slower than one that allocates ten times, and E16 is where that is measured.\n",
    );

    let dir = root().join("results");
    std::fs::create_dir_all(&dir).expect("results/");
    std::fs::write(dir.join("E18-memory.csv"), &csv).expect("write csv");
    std::fs::write(dir.join("E18-memory.md"), &md).expect("write md");

    let mut over = 0;
    for r in &rows {
        let flag = match alloc::budget(r.scenario) {
            Some(b) if r.allocations_per_op() > b => {
                over += 1;
                "OVER BUDGET"
            }
            Some(_) => "ok",
            None => "no budget",
        };
        println!(
            "  {:<22} {:>10.1} alloc/op  {:>12.0} B/op  live {:>10}  peak {:>10}  {}",
            r.scenario,
            r.allocations_per_op(),
            r.bytes_per_op(),
            r.counted.live_delta,
            r.counted.peak_delta,
            flag
        );
    }
    println!("\n  wrote results/E18-memory.md and results/E18-memory.csv");
    if over > 0 {
        eprintln!("  {over} scenario(s) are over budget");
        std::process::exit(1);
    }
}
