//! **M2 — contingent schedules.** Future posting sets, declared once, balanced by
//! construction.
//!
//! A schedule is a bitemporally-dated set of *future* posting sets, each becoming effective
//! at a valid-time instant subject to a predicate. It is the mechanism behind forward and
//! swap legs, interest accruals, coupon and amortisation schedules, repayment waterfalls,
//! funds sweep, cash pooling, zero-balance structures, fee runs, and dividend
//! distributions — which is most of what a bank does that is not a single payment.
//!
//! # The property that makes this a mechanism rather than a cron job
//!
//! **A schedule is generated by a rule, and the rule is proved balanced by construction.**
//!
//! The distinction is worth being precise about, because it is the entire value here. A
//! scheduler that stores rows of *amounts* to post later has moved the conservation
//! obligation to a place nobody checks: the rows were balanced when written, the calendar
//! shifted, a leg was regenerated, and now they are not. A schedule that stores a
//! **generator** — a function from an occurrence to a posting set — can be checked once,
//! and then every occurrence it will ever produce is balanced, whatever the calendar does.
//!
//! [`Schedule::generate`] therefore returns posting sets that the kernel will accept, and
//! [`Schedule::check_generator`] verifies the generator against a sample of occurrences
//! before the schedule is ever installed. A generator that can produce an unbalanced set is
//! rejected at declaration time rather than at 3 a.m. on a coupon date.
//!
//! # Contingency
//!
//! Not every occurrence fires. A cap pays only when the index exceeds the strike; a sweep
//! moves only when the balance breaches a threshold; a contingent leg settles only if a
//! credit event has not occurred. [`Contingency`] is the predicate, evaluated against
//! observations at the occurrence date, and a schedule whose contingency is false produces
//! **no posting set at all** rather than a zero one — because "nothing happened" and "a
//! zero-value thing happened" are different facts and an auditor will ask which.
//!
//! # Why occurrences are computed and never stored
//!
//! An occurrence is derived from the schedule's rule and a date, so it is a function of
//! data that is already immutable. Storing the list would create a second source of truth
//! that a business-day-convention change could desynchronise — and business-day conventions
//! do change, because holiday calendars are amended.

use gbs_kernel::{Amount, PostingSet, Stamp, Epoch};
use std::fmt;

/// How a date that falls on a non-business day is adjusted.
///
/// These are the ISDA conventions, and they are here rather than in a product because every
/// product needs them and each would otherwise implement its own — which is how two legs of
/// one swap come to settle on different days.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RollConvention {
    /// Take the date as it falls. Correct for accrual arithmetic, wrong for settlement.
    None,
    /// Move to the next business day.
    Following,
    /// Next business day, unless that crosses into the next month, in which case previous.
    ///
    /// The default in practice, and the one whose month-end behaviour is most often got
    /// wrong: the whole point is that a payment scheduled for the 31st does not slide into
    /// the following month and change which accrual period it belongs to.
    ModifiedFollowing,
    /// Move to the previous business day.
    Preceding,
}

/// A calendar, as a predicate on valid-time days.
///
/// A trait rather than a table, because a real deployment has several — TARGET, New York,
/// London, a currency-pair union — and a schedule names which it uses. Defaulting to one
/// hidden global calendar is how a EUR leg comes to be rolled over a US holiday.
pub trait Calendar {
    fn is_business_day(&self, day: i64) -> bool;

    fn month_of(&self, day: i64) -> i64 {
        // A deliberately crude 30-day month, sufficient for the roll logic's *decision*
        // (did we cross a month boundary?) without pulling in a calendar library. A
        // production deployment supplies a real implementation; the trait is the seam.
        day.div_euclid(30)
    }
}

/// Every day is a business day. For accrual schedules, and for tests.
#[derive(Debug, Clone, Copy, Default)]
pub struct AllDays;

impl Calendar for AllDays {
    fn is_business_day(&self, _day: i64) -> bool {
        true
    }
}

/// A five-day week with no holidays. Day 0 is a Monday.
#[derive(Debug, Clone, Copy, Default)]
pub struct Weekdays;

impl Calendar for Weekdays {
    fn is_business_day(&self, day: i64) -> bool {
        day.rem_euclid(7) < 5
    }
}

impl RollConvention {
    /// Adjust `day` to a business day under `cal`.
    ///
    /// Bounded at 14 iterations. An unbounded search would hang on a pathological calendar,
    /// and a scheduler that hangs on a coupon date is worse than one that reports it cannot
    /// find a business day.
    pub fn adjust<C: Calendar>(&self, day: i64, cal: &C) -> Option<i64> {
        if matches!(self, RollConvention::None) || cal.is_business_day(day) {
            return Some(day);
        }
        let step = |d: i64, forward: bool| if forward { d + 1 } else { d - 1 };
        let forward = !matches!(self, RollConvention::Preceding);
        let mut d = day;
        for _ in 0..14 {
            d = step(d, forward);
            if cal.is_business_day(d) {
                if matches!(self, RollConvention::ModifiedFollowing)
                    && cal.month_of(d) != cal.month_of(day)
                {
                    // Crossed a month; go back instead. The month-end behaviour that
                    // decides which accrual period a payment belongs to.
                    return RollConvention::Preceding.adjust(day, cal);
                }
                return Some(d);
            }
        }
        None
    }
}

/// One scheduled event: a date, and the sequence number within the schedule.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Occurrence {
    /// Zero-based index within the schedule. Carried so a generator can compute a declining
    /// balance, a step-up coupon, or a final-period stub without re-deriving where it is.
    pub index: u32,
    /// The unadjusted date the rule produced.
    pub scheduled: i64,
    /// The date after roll adjustment — when value actually moves.
    pub adjusted: i64,
    /// The previous occurrence's adjusted date, for day-count fractions. `None` on the
    /// first, where the accrual start is the schedule's effective date.
    pub previous: Option<i64>,
    /// Whether this is the final occurrence. Generators need it: the last period usually
    /// repays principal as well as interest, and a stub period is shorter.
    pub is_final: bool,
}

impl Occurrence {
    /// Days in this period. Used by every day-count fraction.
    pub fn accrual_days(&self, effective: i64) -> i64 {
        self.adjusted - self.previous.unwrap_or(effective)
    }
}

/// Whether an occurrence fires.
///
/// Evaluated against observations at the occurrence date. A false contingency produces **no
/// posting set**, not a zero one — "nothing happened" and "a zero-value thing happened" are
/// different facts.
pub enum Contingency {
    /// Fires every time. Amortisation, fixed coupons, sweeps with no threshold.
    Always,
    /// Fires when the predicate holds. The observation is passed in rather than fetched, so
    /// the decision is reproducible at an epoch: the same observation gives the same answer
    /// forever, which `reproduce e at #4200` requires.
    When(Box<dyn Fn(&Occurrence, &Observations) -> bool>),
}

impl fmt::Debug for Contingency {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Contingency::Always => f.write_str("Always"),
            Contingency::When(_) => f.write_str("When(<predicate>)"),
        }
    }
}

impl Contingency {
    pub fn fires(&self, occ: &Occurrence, obs: &Observations) -> bool {
        match self {
            Contingency::Always => true,
            Contingency::When(p) => p(occ, obs),
        }
    }
}

/// The external facts an occurrence's contingency and generator may consult.
///
/// Passed in rather than fetched. This is the determinism obligation of Appendix C.4
/// reaching into scheduling: a generator that read a rate from a live feed would produce a
/// different posting set on every replay, and the schedule could not be reproduced at an
/// epoch. What it observed must be a recorded fact, so it is an argument.
#[derive(Debug, Clone, Default)]
pub struct Observations {
    fixings: std::collections::BTreeMap<String, i128>,
    /// The scale each fixing is quoted at, so a rate of `52_500` is unambiguously 5.25%
    /// rather than 52,500%.
    scales: std::collections::BTreeMap<String, u32>,
}

impl Observations {
    pub fn new() -> Self {
        Observations::default()
    }

    /// Record a fixing: an index value at a scale. `fix("SOFR", 52_500, 6)` is 5.25%.
    pub fn fix(mut self, index: &str, value: i128, scale: u32) -> Self {
        self.fixings.insert(index.to_string(), value);
        self.scales.insert(index.to_string(), scale);
        self
    }

    /// The fixing, or `None`.
    ///
    /// **`None`, never zero.** A missing rate fixing is honest absence (thesis §3.3): a cap
    /// whose index did not fix must not be priced as though the index were zero, which
    /// would make every cap pay out. This is the `Err(_) => 0` defect of §1.1.1, in the one
    /// place it would cost the most.
    pub fn get(&self, index: &str) -> Option<(i128, u32)> {
        Some((*self.fixings.get(index)?, *self.scales.get(index)?))
    }

    pub fn has(&self, index: &str) -> bool {
        self.fixings.contains_key(index)
    }
}

/// What a schedule refuses.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ScheduleError {
    /// The generator produced an unbalanced posting set for some occurrence.
    ///
    /// Reported at *declaration* time by [`Schedule::check_generator`], which is the whole
    /// design: a schedule that could ever produce an unbalanced set is rejected before it is
    /// installed, rather than failing on a coupon date years later.
    GeneratorNotConserving { index: u32, detail: String },
    /// No business day found within the search bound.
    NoBusinessDay { day: i64 },
    /// A fixing the generator needed was absent. Not defaulted to zero.
    MissingFixing { index: String, at: i64 },
    /// A schedule with no occurrences.
    Empty,
    /// A period of zero or negative length — a maturity before the effective date, or a
    /// frequency of zero.
    BadTenor { effective: i64, maturity: i64, every_days: i64 },
}

impl fmt::Display for ScheduleError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ScheduleError::GeneratorNotConserving { index, detail } => write!(
                f,
                "the generator produces an unbalanced posting set at occurrence {index}: \
                 {detail}. A schedule must be balanced by construction, for every \
                 occurrence it will ever produce"
            ),
            ScheduleError::NoBusinessDay { day } => {
                write!(f, "no business day found within 14 days of {day}")
            }
            ScheduleError::MissingFixing { index, at } => write!(
                f,
                "fixing `{index}` is absent at day {at}. A missing fixing is not zero; the \
                 occurrence cannot be priced"
            ),
            ScheduleError::Empty => write!(f, "a schedule must have at least one occurrence"),
            ScheduleError::BadTenor { effective, maturity, every_days } => write!(
                f,
                "cannot build a schedule from day {effective} to {maturity} every \
                 {every_days} days"
            ),
        }
    }
}

/// A generator: from an occurrence and its observations, a posting set — or nothing.
///
/// `Option` in the return, because a generator may legitimately decline: a sweep whose
/// balance is already at target moves nothing, and returning an empty posting set would be
/// refused by the kernel as [`Empty`](gbs_kernel::KernelError::Empty). The two layers agree
/// that "no movement" is not a transaction.
pub type Generator = Box<dyn Fn(&Occurrence, &Observations) -> Option<PostingSet>>;

/// A contingent schedule.
pub struct Schedule {
    pub name: String,
    pub effective: i64,
    pub maturity: i64,
    pub every_days: i64,
    pub roll: RollConvention,
    pub contingency: Contingency,
    generator: Generator,
}

impl fmt::Debug for Schedule {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Schedule")
            .field("name", &self.name)
            .field("effective", &self.effective)
            .field("maturity", &self.maturity)
            .field("every_days", &self.every_days)
            .field("roll", &self.roll)
            .field("contingency", &self.contingency)
            .finish_non_exhaustive()
    }
}

impl Schedule {
    pub fn new(
        name: impl Into<String>,
        effective: i64,
        maturity: i64,
        every_days: i64,
        generator: Generator,
    ) -> Result<Self, ScheduleError> {
        if every_days <= 0 || maturity <= effective {
            return Err(ScheduleError::BadTenor { effective, maturity, every_days });
        }
        Ok(Schedule {
            name: name.into(),
            effective,
            maturity,
            every_days,
            roll: RollConvention::ModifiedFollowing,
            contingency: Contingency::Always,
            generator,
        })
    }

    pub fn with_roll(mut self, r: RollConvention) -> Self {
        self.roll = r;
        self
    }

    pub fn contingent_on(mut self, c: Contingency) -> Self {
        self.contingency = c;
        self
    }

    /// The occurrence dates, computed from the rule.
    ///
    /// Never stored. See the module docs: a stored list is a second source of truth that a
    /// calendar amendment desynchronises.
    pub fn occurrences<C: Calendar>(&self, cal: &C) -> Result<Vec<Occurrence>, ScheduleError> {
        let mut out = Vec::new();
        let mut day = self.effective + self.every_days;
        let mut index = 0u32;
        let mut previous: Option<i64> = None;

        while day <= self.maturity {
            let adjusted = self
                .roll
                .adjust(day, cal)
                .ok_or(ScheduleError::NoBusinessDay { day })?;
            out.push(Occurrence {
                index,
                scheduled: day,
                adjusted,
                previous,
                is_final: day + self.every_days > self.maturity,
            });
            previous = Some(adjusted);
            day += self.every_days;
            index += 1;
        }

        if out.is_empty() {
            return Err(ScheduleError::Empty);
        }
        Ok(out)
    }

    /// **The declaration-time check.** Verify that the generator conserves for every
    /// occurrence, given the observations supplied.
    ///
    /// This is what "balanced by construction" means operationally. It runs before the
    /// schedule is installed, so a generator that could ever produce an unbalanced set is
    /// rejected at the point where somebody is looking at it — not on a coupon date.
    ///
    /// The check is only as strong as the observations supplied, and that limit is real: a
    /// generator whose imbalance depends on a rate outside the sample will not be caught
    /// here. It *will* be caught by the kernel at posting time, so the failure is loud
    /// rather than silent — but the value of this check is catching it earlier, and callers
    /// should sample the boundaries.
    pub fn check_generator<C: Calendar>(
        &self,
        cal: &C,
        chart: &gbs_kernel::Chart,
        samples: &[Observations],
    ) -> Result<(), ScheduleError> {
        for occ in self.occurrences(cal)? {
            for obs in samples {
                if !self.contingency.fires(&occ, obs) {
                    continue;
                }
                if let Some(ps) = (self.generator)(&occ, obs) {
                    if let Err(e) = ps.seal(chart, Epoch(0)) {
                        return Err(ScheduleError::GeneratorNotConserving {
                            index: occ.index,
                            detail: e.to_string(),
                        });
                    }
                }
            }
        }
        Ok(())
    }

    /// Generate the posting sets that fire on `as_of`, stamped at `epoch`.
    ///
    /// Returns only occurrences whose adjusted date is exactly `as_of` and whose contingency
    /// fires. Every set returned is balanced, because the generator was checked.
    pub fn generate<C: Calendar>(
        &self,
        cal: &C,
        as_of: i64,
        epoch: Epoch,
        obs: &Observations,
    ) -> Result<Vec<(Occurrence, PostingSet)>, ScheduleError> {
        let _ = Stamp::new(epoch, as_of);
        let mut out = Vec::new();
        for occ in self.occurrences(cal)? {
            if occ.adjusted != as_of || !self.contingency.fires(&occ, obs) {
                continue;
            }
            if let Some(ps) = (self.generator)(&occ, obs) {
                out.push((occ, ps));
            }
        }
        Ok(out)
    }
}

/// Split an amount into `n` equal instalments that sum exactly to the whole.
///
/// The same conservation problem M4 solves, arising here for amortisation. Delegating to
/// [`ParticipantSet`](crate::ParticipantSet) would be over-machinery for the even case, so
/// this does the simple thing exactly: the remainder goes to the **final** instalment, which
/// is where loan documents put it.
pub fn equal_instalments(total: &Amount, n: u32) -> Vec<Amount> {
    if n == 0 {
        return Vec::new();
    }
    let n = n as i128;
    let base = total.minor.div_euclid(n);
    let remainder = total.minor - base * n;
    (0..n)
        .map(|i| {
            let m = if i == n - 1 { base + remainder } else { base };
            Amount::new(m, total.currency.clone(), total.scale)
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use gbs_kernel::{Account, Chart, Entry};

    fn chart() -> Chart {
        Chart::new()
            .with(Account::new("loan.usd", "cust-1", "USD"))
            .with(Account::new("interest.usd", "bank", "USD"))
            .with(Account::new("cash.usd", "bank", "USD"))
    }

    /// A coupon generator: debit interest income, credit the loan. Balanced by construction
    /// because the credit is the debit's mirror — there is no path by which it can differ.
    fn coupon(minor: i128) -> Generator {
        Box::new(move |occ, _obs| {
            let d = Entry::new(
                occ.index as u64 * 2,
                "interest.usd",
                Amount::minor_2dp(-minor, "USD"),
                Stamp::new(Epoch(0), occ.adjusted),
            );
            let c = d.mirrored_to(occ.index as u64 * 2 + 1, "loan.usd").ok()?;
            Some(PostingSet::new(format!("coupon-{}", occ.index)).with(d).with(c))
        })
    }

    // ── occurrence generation ───────────────────────────────────────────────────────

    #[test]
    fn a_quarterly_schedule_over_a_year_has_four_occurrences() {
        let s = Schedule::new("q", 0, 360, 90, coupon(100)).unwrap();
        let occ = s.occurrences(&AllDays).unwrap();
        assert_eq!(occ.len(), 4);
        assert_eq!(occ.iter().map(|o| o.adjusted).collect::<Vec<_>>(), vec![90, 180, 270, 360]);
        assert!(occ[3].is_final);
        assert!(!occ[0].is_final);
    }

    #[test]
    fn occurrences_chain_so_a_day_count_fraction_can_be_computed() {
        let s = Schedule::new("q", 0, 360, 90, coupon(100)).unwrap();
        let occ = s.occurrences(&AllDays).unwrap();
        assert_eq!(occ[0].previous, None, "the first accrues from the effective date");
        assert_eq!(occ[0].accrual_days(0), 90);
        assert_eq!(occ[1].previous, Some(90));
        assert_eq!(occ[1].accrual_days(0), 90);
    }

    #[test]
    fn occurrences_are_computed_and_never_stored() {
        // Two calls must agree, and calling with a *different* calendar must give a
        // different answer — which is only possible if the list is derived.
        // Every 5 days from day 0: 5, 10, 15, 20, 25, 30. Under `Weekdays` (day 0 is a
        // Monday) days 5 and 20 fall on weekends and must roll — so the two calendars
        // genuinely disagree. An earlier version of this test used a 7-day period, where
        // every occurrence lands on a Monday and both calendars agree; it passed for the
        // wrong reason, which is worse than failing.
        let s = Schedule::new("q", 0, 30, 5, coupon(100)).unwrap();
        let a = s.occurrences(&AllDays).unwrap();
        let b = s.occurrences(&AllDays).unwrap();
        assert_eq!(a, b, "same calendar, same answer");

        let c = s.occurrences(&Weekdays).unwrap();
        assert_ne!(a, c, "the calendar changes the answer, so the list cannot be stored");
        assert_eq!(a.iter().map(|o| o.adjusted).collect::<Vec<_>>(), vec![5, 10, 15, 20, 25, 30]);
        assert_eq!(
            c.iter().map(|o| o.adjusted).collect::<Vec<_>>(),
            vec![7, 10, 15, 21, 25, 30],
            "day 5 (Sat) rolls to 7, day 20 (Sun) rolls to 21"
        );
    }

    #[test]
    fn a_maturity_before_the_effective_date_is_refused() {
        assert!(matches!(
            Schedule::new("bad", 100, 50, 10, coupon(1)),
            Err(ScheduleError::BadTenor { .. })
        ));
        assert!(matches!(
            Schedule::new("bad", 0, 100, 0, coupon(1)),
            Err(ScheduleError::BadTenor { .. })
        ));
    }

    // ── roll conventions ────────────────────────────────────────────────────────────

    #[test]
    fn following_moves_forward_off_a_weekend() {
        // Day 5 is a Saturday under `Weekdays`; day 7 is the next Monday.
        assert_eq!(RollConvention::Following.adjust(5, &Weekdays), Some(7));
        assert_eq!(RollConvention::Following.adjust(4, &Weekdays), Some(4), "a Friday is fine");
    }

    #[test]
    fn preceding_moves_backward() {
        assert_eq!(RollConvention::Preceding.adjust(5, &Weekdays), Some(4));
        assert_eq!(RollConvention::Preceding.adjust(6, &Weekdays), Some(4));
    }

    #[test]
    fn none_leaves_the_date_alone_which_is_what_accrual_arithmetic_wants() {
        assert_eq!(RollConvention::None.adjust(5, &Weekdays), Some(5));
    }

    #[test]
    fn modified_following_does_not_cross_a_month_boundary() {
        // The behaviour most often got wrong, and the reason it matters: a payment that
        // slides into the next month changes which accrual period it belongs to.
        // Under the default 30-day `month_of`, days 0..=29 are month 0 and day 30 begins
        // month 1. Make days 28 and 29 non-business, so a payment scheduled for the 29th
        // must move — and Following would move it to day 30, into the next month.
        struct MonthEnd;
        impl Calendar for MonthEnd {
            fn is_business_day(&self, day: i64) -> bool {
                !matches!(day, 8 | 28 | 29)
            }
        }
        assert_eq!(RollConvention::Following.adjust(29, &MonthEnd), Some(30));
        assert_eq!(
            RollConvention::ModifiedFollowing.adjust(29, &MonthEnd),
            Some(27),
            "modified-following goes back rather than crossing the month"
        );
        // Day 28 crosses too — Following would reach 30, the next month — so it also
        // rolls back rather than forward.
        assert_eq!(RollConvention::ModifiedFollowing.adjust(28, &MonthEnd), Some(27));

        // And mid-month, where no boundary is crossed, modified-following behaves exactly
        // like following. Otherwise the "modified" part would be changing dates it has no
        // business changing, which is the failure mode in the opposite direction.
        assert_eq!(RollConvention::Following.adjust(8, &MonthEnd), Some(9));
        assert_eq!(RollConvention::ModifiedFollowing.adjust(8, &MonthEnd), Some(9));
    }

    #[test]
    fn a_calendar_with_no_business_days_reports_rather_than_hangs() {
        struct Never;
        impl Calendar for Never {
            fn is_business_day(&self, _: i64) -> bool {
                false
            }
        }
        assert_eq!(RollConvention::Following.adjust(1, &Never), None);
        let s = Schedule::new("q", 0, 90, 30, coupon(1)).unwrap();
        assert!(matches!(
            s.occurrences(&Never),
            Err(ScheduleError::NoBusinessDay { .. })
        ));
    }

    // ── balanced by construction ────────────────────────────────────────────────────

    #[test]
    fn a_conserving_generator_passes_the_declaration_time_check() {
        let s = Schedule::new("q", 0, 360, 90, coupon(5_000)).unwrap();
        s.check_generator(&AllDays, &chart(), &[Observations::new()])
            .expect("a mirrored pair always conserves");
    }

    #[test]
    fn an_unbalanced_generator_is_caught_at_declaration_and_names_the_occurrence() {
        // The whole point of the mechanism. This generator credits one cent less than it
        // debits — the classic fat-finger — and it is rejected before the schedule is
        // installed rather than on a coupon date.
        let broken: Generator = Box::new(|occ, _| {
            Some(
                PostingSet::new(format!("bad-{}", occ.index))
                    .with(Entry::new(
                        1,
                        "interest.usd",
                        Amount::minor_2dp(-5_000, "USD"),
                        Stamp::new(Epoch(0), occ.adjusted),
                    ))
                    .with(Entry::new(
                        2,
                        "loan.usd",
                        Amount::minor_2dp(4_999, "USD"),
                        Stamp::new(Epoch(0), occ.adjusted),
                    )),
            )
        });
        let s = Schedule::new("q", 0, 360, 90, broken).unwrap();
        let e = s.check_generator(&AllDays, &chart(), &[Observations::new()]).unwrap_err();
        assert!(matches!(e, ScheduleError::GeneratorNotConserving { index: 0, .. }));
        let msg = e.to_string();
        assert!(msg.contains("occurrence 0"), "{msg}");
        assert!(msg.contains("balanced by construction"), "{msg}");
    }

    #[test]
    fn every_generated_set_seals_against_the_kernel() {
        // The end-to-end property: what the schedule produces is what the ledger accepts.
        let s = Schedule::new("q", 0, 360, 90, coupon(5_000)).unwrap();
        let ch = chart();
        for day in [90, 180, 270, 360] {
            let out = s.generate(&AllDays, day, Epoch(7), &Observations::new()).unwrap();
            assert_eq!(out.len(), 1, "exactly one occurrence on day {day}");
            out[0].1.clone().seal(&ch, Epoch(7)).expect("balanced");
        }
        assert!(s.generate(&AllDays, 91, Epoch(7), &Observations::new()).unwrap().is_empty());
    }

    // ── contingency ─────────────────────────────────────────────────────────────────

    #[test]
    fn a_contingency_that_does_not_fire_produces_nothing_rather_than_a_zero_posting() {
        // "Nothing happened" and "a zero-value thing happened" are different facts, and an
        // auditor will ask which. A cap below its strike did not pay; it did not pay zero.
        let s = Schedule::new("cap", 0, 360, 90, coupon(5_000))
            .unwrap()
            .contingent_on(Contingency::When(Box::new(|_occ, obs| {
                matches!(obs.get("SOFR"), Some((v, _)) if v > 50_000)
            })));

        let above = Observations::new().fix("SOFR", 60_000, 6);
        let below = Observations::new().fix("SOFR", 40_000, 6);

        assert_eq!(s.generate(&AllDays, 90, Epoch(1), &above).unwrap().len(), 1);
        assert!(
            s.generate(&AllDays, 90, Epoch(1), &below).unwrap().is_empty(),
            "below the strike, the cap produces no posting set at all"
        );
    }

    #[test]
    fn a_missing_fixing_is_absent_and_never_zero() {
        // The `Err(_) => 0` defect of §1.1.1, in the place it would cost most: an index that
        // did not fix must not be read as zero, or every cap pays out and every floor does
        // not.
        let obs = Observations::new().fix("SOFR", 52_500, 6);
        assert_eq!(obs.get("SOFR"), Some((52_500, 6)));
        assert_eq!(obs.get("ESTR"), None, "absent, not zero");
        assert!(!obs.has("ESTR"));

        // And a cap contingent on an absent index does not fire.
        let s = Schedule::new("cap", 0, 180, 90, coupon(1))
            .unwrap()
            .contingent_on(Contingency::When(Box::new(|_, obs| {
                matches!(obs.get("ESTR"), Some((v, _)) if v > 0)
            })));
        assert!(s.generate(&AllDays, 90, Epoch(1), &obs).unwrap().is_empty());
    }

    #[test]
    fn observations_are_passed_in_so_generation_is_reproducible() {
        // Determinism: the same observations give the same posting sets, forever. A
        // generator that read a live feed could not be reproduced at an epoch.
        let s = Schedule::new("q", 0, 90, 90, coupon(1_234)).unwrap();
        let obs = Observations::new().fix("SOFR", 52_500, 6);
        let first = s.generate(&AllDays, 90, Epoch(3), &obs).unwrap();
        for _ in 0..20 {
            assert_eq!(s.generate(&AllDays, 90, Epoch(3), &obs).unwrap(), first);
        }
    }

    #[test]
    fn a_generator_may_decline_and_that_is_not_an_empty_posting_set() {
        // A sweep already at target moves nothing. Returning an empty set would be refused
        // by the kernel as `Empty`; returning `None` is the two layers agreeing that no
        // movement is not a transaction.
        let declines: Generator = Box::new(|_, _| None);
        let s = Schedule::new("sweep", 0, 90, 30, declines).unwrap();
        assert!(s.generate(&AllDays, 30, Epoch(1), &Observations::new()).unwrap().is_empty());
        s.check_generator(&AllDays, &chart(), &[Observations::new()]).unwrap();
    }

    // ── amortisation ────────────────────────────────────────────────────────────────

    #[test]
    fn equal_instalments_sum_exactly_to_the_principal() {
        // $1,000.00 over 7 instalments: 100000/7 = 14285.71…, and the remainder must go
        // somewhere rather than evaporate.
        for (total, n) in [(100_000i128, 7u32), (100i128, 3), (1, 5), (0, 4), (999_999, 12)] {
            let parts = equal_instalments(&Amount::minor_2dp(total, "USD"), n);
            assert_eq!(parts.len(), n as usize);
            assert_eq!(parts.iter().map(|a| a.minor).sum::<i128>(), total, "total={total} n={n}");
        }
    }

    #[test]
    fn the_amortisation_remainder_lands_on_the_final_instalment() {
        // Where loan documents put it: the balancing payment is the last one.
        let parts = equal_instalments(&Amount::minor_2dp(100_000, "USD"), 7);
        assert_eq!(parts[0].minor, 14_285);
        assert_eq!(parts[6].minor, 14_290, "14285 + the 5-cent remainder");
    }

    #[test]
    fn a_negative_total_amortises_without_drifting() {
        // A refund schedule. `div_euclid` rather than `/` is what keeps this exact for
        // negatives — truncating division would round toward zero and leave a residue.
        let parts = equal_instalments(&Amount::minor_2dp(-100_000, "USD"), 7);
        assert_eq!(parts.iter().map(|a| a.minor).sum::<i128>(), -100_000);
    }

    #[test]
    fn zero_instalments_produces_nothing_rather_than_dividing_by_zero() {
        assert!(equal_instalments(&Amount::minor_2dp(100, "USD"), 0).is_empty());
    }
}
