[package]
name = "nilestream"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "nilestream"
path = "src/main.rs"

[dependencies]
niles-lang = { path = "../niles-lang" }
niles-ir = { path = "../niles-ir" }
nilestream-core = { path = "../nilestream-core" }
proto-engine = { path = "../proto-engine" }
